etitle: Vasili Srinivas
description: >
  Senior R&D Professional | Refrigeration Systems |
  Global R&D Leadership | Data & AI Engineering

theme: jekyll-theme-minimal

show_downloads: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

exclude:
  - README.md
  - node_modules
  - vendor
